name : the PR gatekeeper

on: 
    pull_request:
      branches:
        - main
    workflow_dispatch:

jobs:
    checks:
      runs-on: ubuntu-latest

      steps:
        - name: Print target Branch
          run: echo "PR is being mergerd into ${{github.base.ref}}"

        - name: Print PR number
          run: echo "PR number is ${{github.event.pull_request.number}}"
        
        - name: Complete check
          run: echo "Gatekeeper checks complete"