name: Release Watcher

on: 
    push:
        branches:
            - main
    schedule:
        - cron: '0 9 * * 1'
    workflow_dispatch:

jobs:
    watch:
        runs-on: ubuntu-latest
        
        steps:
            - name: Print Evennt name
              run: |
                echo "Event: ${{github.event_name}}"
                echo "Curent date and time:"
                date

            - name: Complete release watch 
              run: echo "Release watch complete"

